# Generated by Django 5.2.10 on 2026-01-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_mockexam_question_mock_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='content',
        ),
        migrations.AddField(
            model_name='summary',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='summaries/'),
        ),
    ]
