# Generated by Django 5.2.10 on 2026-01-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_summary_content_summary_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockexam',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='mockexam',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='question',
            name='mock_exam',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
