# Generated by Django 5.2.10 on 2026-01-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_mockexam_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
    ]
