# Generated by Django 5.2.15 on 2026-06-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_fillinthegap'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_type',
            field=models.CharField(choices=[('CBT', 'Computer-Based Test (100-200 Level)'), ('POP', 'Pen-On-Paper (300+ Level)')], default='CBT', max_length=3),
        ),
    ]
